# Generated by Django 5.2.17 on 2026-09-29 05:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New chat', max_length=120)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI API'), ('anthropic', 'Anthropic API'), ('google', 'Google Gemini API')], max_length=20)),
                ('model_id', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'indexes': [models.Index(fields=['-updated_at', '-id'], name='chat_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=12)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=12)),
                ('provider', models.CharField(blank=True, choices=[('openai', 'OpenAI API'), ('anthropic', 'Anthropic API'), ('google', 'Google Gemini API')], max_length=20)),
                ('model_id', models.CharField(blank=True, max_length=120)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['conversation', 'created_at', 'id'], name='chat_msg_order_idx')],
            },
        ),
    ]
