# Generated by Django 5.2.17 on 2026-09-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['openai', 'anthropic', 'google'])), name='chat_convo_provider_ck'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('user', 'assistant'))), name='chat_msg_role_ck'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'completed', 'failed'))), name='chat_msg_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['openai', 'anthropic', 'google']), ('provider', ''), _connector='OR'), name='chat_msg_provider_ck'),
        ),
    ]
